# Generated by Django 3.2.13 on 2022-06-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ventas', models.IntegerField(max_length=8)),
                ('crecimiento', models.IntegerField(max_length=8)),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
    ]
